---
name: Pod-POM-View-HTML-Filter
version: 0.06
author:
  - 'Philippe "BooK" Bruhat <book@cpan.org>'
abstract: Use filters on sections of your pod documents
license: perl
requires:
  Pod::POM: 0.17
  Test::More: 0
recommends:
  Perl::Tidy: 20031021
  Syntax::Highlight::HTML: 0.02
  Syntax::Highlight::Shell: 0.02
provides:
  Pod::POM::View::HTML::Filter:
    file: lib/Pod/POM/View/HTML/Filter.pm
    version: 0.06
generated_by: Module::Build version 0.26
